replicaCount: 1

image:
  repository: rahulbohra57/healthifyme-app
  tag: 214452d
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8501

env:
  secretName: gemini-api-secret
  apiKey: GOOGLE_API_KEY1